// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CRM.UITest.Scripts.Shipment.AddShipmentLTL2019
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class _76046_AddShipmentLTL2019_ShippingFromTo_SaveOriginDestinationInfoFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "76046 - Add Shipment (LTL) 2019 - Shipping FromTo - Save OriginDestination Info.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "76046 - Add Shipment (LTL) 2019 - Shipping FromTo - Save OriginDestination Info", null, ProgrammingLanguage.CSharp, new string[] {
                        "Sprint90",
                        "76046"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "76046 - Add Shipment (LTL) 2019 - Shipping FromTo - Save OriginDestination Info")))
            {
                global::CRM.UITest.Scripts.Shipment.AddShipmentLTL2019._76046_AddShipmentLTL2019_ShippingFromTo_SaveOriginDestinationInfoFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("76046 - Verify if Shipping From section details are getting saved when user click" +
            "s on Save Origin info button_ExternalUser")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "76046 - Add Shipment (LTL) 2019 - Shipping FromTo - Save OriginDestination Info")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint90")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("76046")]
        public virtual void _76046_VerifyIfShippingFromSectionDetailsAreGettingSavedWhenUserClicksOnSaveOriginInfoButton_ExternalUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("76046 - Verify if Shipping From section details are getting saved when user click" +
                    "s on Save Origin info button_ExternalUser", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("I am a  shp.entry, shp.entrynorates user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
 testRunner.And("I am on the Add Shipment (LTL) page for an External user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.And("I entered all required information in the Add Shipment (LTL) page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.And("I checked the Save Origin info button in the Shipping From section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.When("I Click on the View Rates Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
 testRunner.Then(@"CRM will save the following information of Shipping From section as a saved address for the associated customer: LocationName, LocationAddress, LocationAddress2, ZipOrPostal, Country, City, StateOrProvince, ContactName, ContactPhone, ContactPhoneExt, ContactEmail, ContactFax, ContactFaxExt", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("76046 - Verify if Shipping To section details are getting saved when user clicks " +
            "on Save Destination info button_ExternalUser")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "76046 - Add Shipment (LTL) 2019 - Shipping FromTo - Save OriginDestination Info")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint90")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("76046")]
        public virtual void _76046_VerifyIfShippingToSectionDetailsAreGettingSavedWhenUserClicksOnSaveDestinationInfoButton_ExternalUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("76046 - Verify if Shipping To section details are getting saved when user clicks " +
                    "on Save Destination info button_ExternalUser", ((string[])(null)));
#line 14
this.ScenarioSetup(scenarioInfo);
#line 15
 testRunner.Given("I am a  shp.entry, shp.entrynorates user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 16
 testRunner.And("I am on the Add Shipment (LTL) page for an External user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.And("I entered all required information in the Add Shipment (LTL) page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.And("I checked the Save Destination info button in the Shipping To section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
 testRunner.When("I Click on the View Rates Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 20
 testRunner.Then(@"CRM will save the following information of Shipping To section as a saved address for the associated customer: LocationName, LocationAddress, LocationAddress2, ZipOrPostal, Country, City, StateOrProvince, ContactName, ContactPhone, ContactPhoneExt, ContactEmail, ContactFax, ContactFaxExt", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("76046 - Verify if duplicate address is getting saved by duplicating the informati" +
            "on in the Shipping To section same as Shipping From section and checking Save Or" +
            "igin info button_ExternalUser")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "76046 - Add Shipment (LTL) 2019 - Shipping FromTo - Save OriginDestination Info")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint90")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("76046")]
        public virtual void _76046_VerifyIfDuplicateAddressIsGettingSavedByDuplicatingTheInformationInTheShippingToSectionSameAsShippingFromSectionAndCheckingSaveOriginInfoButton_ExternalUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("76046 - Verify if duplicate address is getting saved by duplicating the informati" +
                    "on in the Shipping To section same as Shipping From section and checking Save Or" +
                    "igin info button_ExternalUser", ((string[])(null)));
#line 22
this.ScenarioSetup(scenarioInfo);
#line 23
 testRunner.Given("I am a  shp.entry, shp.entrynorates user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 24
 testRunner.And("I am on the Add Shipment (LTL) page for an External user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
 testRunner.And("I duplicated already existing saved address details in the Shipping From section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.And("I checked the Save Origin info button in the Shipping From section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
 testRunner.When("I Click on the View Rates Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 28
 testRunner.Then("A duplicate address will not be saved to CRM_Shipping From section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("76046 - Verify if duplicate address is getting saved by duplicating the informati" +
            "on in the Shipping To section same as Shipping From section and checking Save De" +
            "stination info button_ExternalUser")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "76046 - Add Shipment (LTL) 2019 - Shipping FromTo - Save OriginDestination Info")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint90")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("76046")]
        public virtual void _76046_VerifyIfDuplicateAddressIsGettingSavedByDuplicatingTheInformationInTheShippingToSectionSameAsShippingFromSectionAndCheckingSaveDestinationInfoButton_ExternalUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("76046 - Verify if duplicate address is getting saved by duplicating the informati" +
                    "on in the Shipping To section same as Shipping From section and checking Save De" +
                    "stination info button_ExternalUser", ((string[])(null)));
#line 30
this.ScenarioSetup(scenarioInfo);
#line 31
 testRunner.Given("I am a  shp.entry, shp.entrynorates user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 32
 testRunner.And("I am on the Add Shipment (LTL) page for an External user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 33
 testRunner.And("I duplicated already existing saved address details in the Shipping To section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
 testRunner.And("I checked the Save Destination info button in the Shipping To section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 35
 testRunner.When("I Click on the View Rates Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 36
 testRunner.Then("A duplicate address will not be saved to CRM_ShippingTo sectiom", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("76046 - Verify if Shipping From section details are getting saved when user click" +
            "s on Save Origin info button_InternalUser")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "76046 - Add Shipment (LTL) 2019 - Shipping FromTo - Save OriginDestination Info")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint90")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("76046")]
        public virtual void _76046_VerifyIfShippingFromSectionDetailsAreGettingSavedWhenUserClicksOnSaveOriginInfoButton_InternalUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("76046 - Verify if Shipping From section details are getting saved when user click" +
                    "s on Save Origin info button_InternalUser", ((string[])(null)));
#line 40
this.ScenarioSetup(scenarioInfo);
#line 41
 testRunner.Given("I am an operations or a station owner user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 42
 testRunner.And("I am on the Add Shipment (LTL) page for an internal user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 43
 testRunner.And("I entered all required information in the Add Shipment (LTL) page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 44
 testRunner.And("I checked the Save Origin info button in the Shipping From section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 45
 testRunner.When("I Click on the View Rates Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 46
 testRunner.Then(@"CRM will save the following information of Shipping From section as a saved address for the associated customer: LocationName, LocationAddress, LocationAddress2, ZipOrPostal, Country, City, StateOrProvince, ContactName, ContactPhone, ContactPhoneExt, ContactEmail, ContactFax, ContactFaxExt", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("76046 - Verify if Shipping To section details are getting saved when user clicks " +
            "on Save Destination info button_InternalUser")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "76046 - Add Shipment (LTL) 2019 - Shipping FromTo - Save OriginDestination Info")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint90")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("76046")]
        public virtual void _76046_VerifyIfShippingToSectionDetailsAreGettingSavedWhenUserClicksOnSaveDestinationInfoButton_InternalUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("76046 - Verify if Shipping To section details are getting saved when user clicks " +
                    "on Save Destination info button_InternalUser", ((string[])(null)));
#line 48
this.ScenarioSetup(scenarioInfo);
#line 49
 testRunner.Given("I am an operations or a station owner user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 50
 testRunner.And("I am on the Add Shipment (LTL) page for an internal user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
 testRunner.And("I entered all required information in the Add Shipment (LTL) page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 52
 testRunner.And("I checked the Save Destination info button in the Shipping To section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 53
 testRunner.When("I Click on the View Rates Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 54
 testRunner.Then(@"CRM will save the following information of Shipping To section as a saved address for the associated customer: LocationName, LocationAddress, LocationAddress2, ZipOrPostal, Country, City, StateOrProvince, ContactName, ContactPhone, ContactPhoneExt, ContactEmail, ContactFax, ContactFaxExt", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("76046 - Verify if duplicate address is getting saved by duplicating the informati" +
            "on in the Shipping To section same as Shipping From section and checking Save Or" +
            "igin info button_InternalUser")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "76046 - Add Shipment (LTL) 2019 - Shipping FromTo - Save OriginDestination Info")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint90")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("76046")]
        public virtual void _76046_VerifyIfDuplicateAddressIsGettingSavedByDuplicatingTheInformationInTheShippingToSectionSameAsShippingFromSectionAndCheckingSaveOriginInfoButton_InternalUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("76046 - Verify if duplicate address is getting saved by duplicating the informati" +
                    "on in the Shipping To section same as Shipping From section and checking Save Or" +
                    "igin info button_InternalUser", ((string[])(null)));
#line 56
this.ScenarioSetup(scenarioInfo);
#line 57
 testRunner.Given("I am an operations or a station owner user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 58
 testRunner.And("I am on the Add Shipment (LTL) page for an internal user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 59
 testRunner.And("I duplicated already existing saved address details in the Shipping From section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 60
 testRunner.And("I checked the Save Origin info button in the Shipping From section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 61
 testRunner.When("I Click on the View Rates Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 62
 testRunner.Then("A duplicate address will not be saved to CRM_Shipping From section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("76046 - Verify if duplicate address is getting saved by duplicating the informati" +
            "on in the Shipping To section same as Shipping From section and checking Save De" +
            "stination info button_InternalUser")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "76046 - Add Shipment (LTL) 2019 - Shipping FromTo - Save OriginDestination Info")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint90")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("76046")]
        public virtual void _76046_VerifyIfDuplicateAddressIsGettingSavedByDuplicatingTheInformationInTheShippingToSectionSameAsShippingFromSectionAndCheckingSaveDestinationInfoButton_InternalUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("76046 - Verify if duplicate address is getting saved by duplicating the informati" +
                    "on in the Shipping To section same as Shipping From section and checking Save De" +
                    "stination info button_InternalUser", ((string[])(null)));
#line 65
this.ScenarioSetup(scenarioInfo);
#line 66
 testRunner.Given("I am an operations or a station owner user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 67
 testRunner.And("I am on the Add Shipment (LTL) page for an internal user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 68
 testRunner.And("I duplicated already existing saved address details in the Shipping To section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 69
 testRunner.And("I checked the Save Destination info button in the Shipping To section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 70
 testRunner.When("I Click on the View Rates Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 71
 testRunner.Then("A duplicate address will not be saved to CRM_ShippingTo sectiom", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("76046 - Verify if Shipping From section details are getting saved when user click" +
            "s on Save Origin info button_SalesManagementUser")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "76046 - Add Shipment (LTL) 2019 - Shipping FromTo - Save OriginDestination Info")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint90")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("76046")]
        public virtual void _76046_VerifyIfShippingFromSectionDetailsAreGettingSavedWhenUserClicksOnSaveOriginInfoButton_SalesManagementUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("76046 - Verify if Shipping From section details are getting saved when user click" +
                    "s on Save Origin info button_SalesManagementUser", ((string[])(null)));
#line 75
this.ScenarioSetup(scenarioInfo);
#line 76
 testRunner.Given("I am a sales, sales management user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 77
 testRunner.And("I am on the Add Shipment (LTL) page for an internal user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 78
 testRunner.And("I entered all required information in the Add Shipment (LTL) page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 79
 testRunner.And("I checked the Save Origin info button in the Shipping From section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 80
 testRunner.When("I Click on the View Rates Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 81
 testRunner.Then(@"CRM will save the following information of Shipping From section as a saved address for the associated customer: LocationName, LocationAddress, LocationAddress2, ZipOrPostal, Country, City, StateOrProvince, ContactName, ContactPhone, ContactPhoneExt, ContactEmail, ContactFax, ContactFaxExt", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("76046 - Verify if Shipping To section details are getting saved when user clicks " +
            "on Save Destination info button_SalesManagementUser")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "76046 - Add Shipment (LTL) 2019 - Shipping FromTo - Save OriginDestination Info")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint90")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("76046")]
        public virtual void _76046_VerifyIfShippingToSectionDetailsAreGettingSavedWhenUserClicksOnSaveDestinationInfoButton_SalesManagementUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("76046 - Verify if Shipping To section details are getting saved when user clicks " +
                    "on Save Destination info button_SalesManagementUser", ((string[])(null)));
#line 83
this.ScenarioSetup(scenarioInfo);
#line 84
 testRunner.Given("I am a sales, sales management user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 85
 testRunner.And("I am on the Add Shipment (LTL) page for an internal user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 86
 testRunner.And("I entered all required information in the Add Shipment (LTL) page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 87
 testRunner.And("I checked the Save Destination info button in the Shipping To section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 88
 testRunner.When("I Click on the View Rates Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 89
 testRunner.Then(@"CRM will save the following information of Shipping To section as a saved address for the associated customer: LocationName, LocationAddress, LocationAddress2, ZipOrPostal, Country, City, StateOrProvince, ContactName, ContactPhone, ContactPhoneExt, ContactEmail, ContactFax, ContactFaxExt", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("76046 - Verify if duplicate address is getting saved by duplicating the informati" +
            "on in the Shipping To section same as Shipping From section and checking Save Or" +
            "igin info button_SalesManagementUser")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "76046 - Add Shipment (LTL) 2019 - Shipping FromTo - Save OriginDestination Info")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint90")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("76046")]
        public virtual void _76046_VerifyIfDuplicateAddressIsGettingSavedByDuplicatingTheInformationInTheShippingToSectionSameAsShippingFromSectionAndCheckingSaveOriginInfoButton_SalesManagementUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("76046 - Verify if duplicate address is getting saved by duplicating the informati" +
                    "on in the Shipping To section same as Shipping From section and checking Save Or" +
                    "igin info button_SalesManagementUser", ((string[])(null)));
#line 91
this.ScenarioSetup(scenarioInfo);
#line 92
 testRunner.Given("I am a sales, sales management user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 93
 testRunner.And("I am on the Add Shipment (LTL) page for an internal user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 94
 testRunner.And("I duplicated already existing saved address details in the Shipping From section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 95
 testRunner.And("I checked the Save Origin info button in the Shipping From section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 96
 testRunner.When("I Click on the View Rates Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 97
 testRunner.Then("A duplicate address will not be saved to CRM_Shipping From section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("76046 - Verify if duplicate address is getting saved by duplicating the informati" +
            "on in the Shipping To section same as Shipping From section and checking Save De" +
            "stination info button_SalesManagementUser")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "76046 - Add Shipment (LTL) 2019 - Shipping FromTo - Save OriginDestination Info")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint90")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("76046")]
        public virtual void _76046_VerifyIfDuplicateAddressIsGettingSavedByDuplicatingTheInformationInTheShippingToSectionSameAsShippingFromSectionAndCheckingSaveDestinationInfoButton_SalesManagementUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("76046 - Verify if duplicate address is getting saved by duplicating the informati" +
                    "on in the Shipping To section same as Shipping From section and checking Save De" +
                    "stination info button_SalesManagementUser", ((string[])(null)));
#line 100
this.ScenarioSetup(scenarioInfo);
#line 101
 testRunner.Given("I am a sales, sales management user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 102
 testRunner.And("I am on the Add Shipment (LTL) page for an internal user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 103
 testRunner.And("I duplicated already existing saved address details in the Shipping To section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 104
 testRunner.And("I checked the Save Destination info button in the Shipping To section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 105
 testRunner.When("I Click on the View Rates Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 106
 testRunner.Then("A duplicate address will not be saved to CRM_ShippingTo sectiom", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
