// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CRM.UITest.Scripts.Quote.LTL.ShipmentInformationScreen.OverLength_GetQuoteLTL
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class _40832_OverLength_GetQuoteLTL_SavedItemWithDimensionsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "40832-Over Length - Get Quote (LTL) - Saved Item with Dimensions.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "40832-Over Length - Get Quote (LTL) - Saved Item with Dimensions", null, ProgrammingLanguage.CSharp, new string[] {
                        "Sprint81",
                        "40832",
                        "Functional"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "40832-Over Length - Get Quote (LTL) - Saved Item with Dimensions")))
            {
                global::CRM.UITest.Scripts.Quote.LTL.ShipmentInformationScreen.OverLength_GetQuoteLTL._40832_OverLength_GetQuoteLTL_SavedItemWithDimensionsFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("40832-Verify Length,Width,Height dimension fields when saved item included dimens" +
            "ion type is CM")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "40832-Over Length - Get Quote (LTL) - Saved Item with Dimensions")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint81")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("40832")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("RegressionSuite")]
        public virtual void _40832_VerifyLengthWidthHeightDimensionFieldsWhenSavedItemIncludedDimensionTypeIsCM()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("40832-Verify Length,Width,Height dimension fields when saved item included dimens" +
                    "ion type is CM", new string[] {
                        "RegressionSuite"});
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
testRunner.Given("I am a shp.inquiry, shp.entry, sales, sales management, operations, or station ow" +
                    "ner user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
testRunner.And("I am on the Get Quote (LTL) page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
testRunner.And("I have selected a saved item included dimension and dimension type<CM> values", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
testRunner.When("the dimension type of the saved item is <CM>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
testRunner.Then("the Length,Width,Height dimension fields will be blank", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 12
testRunner.And("the dimension type will be defaulted to <IN>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("40832-Verify Length,Width,Height dimension fields when saved item included dimens" +
            "ion type is METER")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "40832-Over Length - Get Quote (LTL) - Saved Item with Dimensions")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint81")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("40832")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("RegressionSuite")]
        public virtual void _40832_VerifyLengthWidthHeightDimensionFieldsWhenSavedItemIncludedDimensionTypeIsMETER()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("40832-Verify Length,Width,Height dimension fields when saved item included dimens" +
                    "ion type is METER", new string[] {
                        "RegressionSuite"});
#line 15
this.ScenarioSetup(scenarioInfo);
#line 16
testRunner.Given("I am a shp.inquiry, shp.entry, sales, sales management, operations, or station ow" +
                    "ner user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 17
testRunner.And("I am on the Get Quote (LTL) page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
testRunner.And("I have selected a saved item included dimension and dimension type<METER> values", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
testRunner.When("the dimension type of the saved item is <METER>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 20
testRunner.Then("the Length,Width,Height dimension fields will be blank", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 21
testRunner.And("the dimension type will be defaulted to <IN>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Default40832-Verify Length,Width,Height dimension fields when default saved item " +
            "included dimension type is CM")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "40832-Over Length - Get Quote (LTL) - Saved Item with Dimensions")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint81")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("40832")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("RegressionSuite")]
        public virtual void Default40832_VerifyLengthWidthHeightDimensionFieldsWhenDefaultSavedItemIncludedDimensionTypeIsCM()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Default40832-Verify Length,Width,Height dimension fields when default saved item " +
                    "included dimension type is CM", new string[] {
                        "RegressionSuite"});
#line 24
this.ScenarioSetup(scenarioInfo);
#line 25
testRunner.Given("I am a shp.inquiry, shp.entry, sales, sales management, operations, or station ow" +
                    "ner user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 26
testRunner.And("I am on the Get Quote (LTL) page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
testRunner.And("the customer has a default item included dimensions and dimension type<CM> values" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
testRunner.When("the dimension type of the saved item is <CM>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 29
testRunner.Then("the Length,Width,Height dimension fields will be blank", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 30
testRunner.And("the dimension type will be defaulted to <IN>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("40832-Verify Length,Width,Height dimension fields when default saved item include" +
            "d dimension type is METER")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "40832-Over Length - Get Quote (LTL) - Saved Item with Dimensions")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint81")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("40832")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("RegressionSuite")]
        public virtual void _40832_VerifyLengthWidthHeightDimensionFieldsWhenDefaultSavedItemIncludedDimensionTypeIsMETER()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("40832-Verify Length,Width,Height dimension fields when default saved item include" +
                    "d dimension type is METER", new string[] {
                        "RegressionSuite"});
#line 33
this.ScenarioSetup(scenarioInfo);
#line 34
testRunner.Given("I am a shp.inquiry, shp.entry, sales, sales management, operations, or station ow" +
                    "ner user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 35
testRunner.And("I am on the Get Quote (LTL) page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 36
testRunner.And("the customer has a default item included dimensions and dimension type<METER> val" +
                    "ues", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 37
testRunner.When("the dimension type of the saved item is <METER>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 38
testRunner.Then("the Length,Width,Height dimension fields will be blank", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 39
testRunner.And("the dimension type will be defaulted to <IN>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("40832-Verify Length,Width,Height dimension fields when saved item included dimens" +
            "ion type is IN")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "40832-Over Length - Get Quote (LTL) - Saved Item with Dimensions")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint81")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("40832")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("RegressionSuite")]
        public virtual void _40832_VerifyLengthWidthHeightDimensionFieldsWhenSavedItemIncludedDimensionTypeIsIN()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("40832-Verify Length,Width,Height dimension fields when saved item included dimens" +
                    "ion type is IN", new string[] {
                        "RegressionSuite"});
#line 42
this.ScenarioSetup(scenarioInfo);
#line 43
testRunner.Given("I am a shp.inquiry, shp.entry, sales, sales management, operations, or station ow" +
                    "ner user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 44
testRunner.And("I am on the Get Quote (LTL) page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 45
testRunner.And("I have selected a saved item included dimension and dimension type<IN> values", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 46
testRunner.When("the dimension type of the saved item is <IN>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 47
testRunner.Then("the Length,Width,Height,Dimension type dimension fields will get bind <IN>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("40832-Verify Length,Width,Height dimension fields when saved item included dimens" +
            "ion type is FT")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "40832-Over Length - Get Quote (LTL) - Saved Item with Dimensions")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint81")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("40832")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("RegressionSuite")]
        public virtual void _40832_VerifyLengthWidthHeightDimensionFieldsWhenSavedItemIncludedDimensionTypeIsFT()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("40832-Verify Length,Width,Height dimension fields when saved item included dimens" +
                    "ion type is FT", new string[] {
                        "RegressionSuite"});
#line 50
this.ScenarioSetup(scenarioInfo);
#line 51
testRunner.Given("I am a shp.inquiry, shp.entry, sales, sales management, operations, or station ow" +
                    "ner user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 52
testRunner.And("I am on the Get Quote (LTL) page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 53
testRunner.And("I have selected a saved item included dimension and dimension type<FT> values", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 54
testRunner.When("the dimension type of the saved item is <FT>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 55
testRunner.Then("the Length,Width,Height,Dimension type dimension fields will get bind <FT>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("40832-Verify Length,Width,Height dimension fields when default saved item include" +
            "d dimension type is IN")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "40832-Over Length - Get Quote (LTL) - Saved Item with Dimensions")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint81")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("40832")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("RegressionSuite")]
        public virtual void _40832_VerifyLengthWidthHeightDimensionFieldsWhenDefaultSavedItemIncludedDimensionTypeIsIN()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("40832-Verify Length,Width,Height dimension fields when default saved item include" +
                    "d dimension type is IN", new string[] {
                        "RegressionSuite"});
#line 58
this.ScenarioSetup(scenarioInfo);
#line 59
testRunner.Given("I am a shp.inquiry, shp.entry, sales, sales management, operations, or station ow" +
                    "ner user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 60
testRunner.And("I am on the Get Quote (LTL) page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 61
testRunner.And("the customer has a default item included dimensions and dimension type values", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 62
testRunner.When("the dimension type of the saved item is <IN>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 63
testRunner.Then("the Length,Width,Height,Dimension type dimension fields will get bind <IN>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("40832-Verify Length,Width,Height dimension fields when default saved item include" +
            "d dimension type is FT")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "40832-Over Length - Get Quote (LTL) - Saved Item with Dimensions")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint81")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("40832")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("RegressionSuite")]
        public virtual void _40832_VerifyLengthWidthHeightDimensionFieldsWhenDefaultSavedItemIncludedDimensionTypeIsFT()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("40832-Verify Length,Width,Height dimension fields when default saved item include" +
                    "d dimension type is FT", new string[] {
                        "RegressionSuite"});
#line 66
this.ScenarioSetup(scenarioInfo);
#line 67
testRunner.Given("I am a shp.inquiry, shp.entry, sales, sales management, operations, or station ow" +
                    "ner user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 68
testRunner.And("I am on the Get Quote (LTL) page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 69
testRunner.And("the customer has a default item included dimensions and dimension type values", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 70
testRunner.When("the dimension type of the saved item is <FT>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 71
testRunner.Then("the Length,Width,Height,Dimension type dimension fields will get bind <FT>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
