// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CRM.UITest.Scripts.CustomerInvoices.CustomReport.ScheduleReports
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class CustomerInvoice_CreateScheduleReports_MonthlyFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "CustomerInvoice_CreateScheduleReports_Monthly.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CustomerInvoice_CreateScheduleReports_Monthly", null, ProgrammingLanguage.CSharp, new string[] {
                        "Sprint80",
                        "39725"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "CustomerInvoice_CreateScheduleReports_Monthly")))
            {
                global::CRM.UITest.Scripts.CustomerInvoices.CustomReport.ScheduleReports.CustomerInvoice_CreateScheduleReports_MonthlyFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void _39725VerifyTheCreationOfScheduledReportMonthlyBySelectingSpecificDayMonth(string testDataMonth, string testDataSpecificDay, string testDataHours, string testDataMinutes, string testDataMeridiem, string testDataTo, string testDataCC, string testDataReplyTo, string testDataFormat, string testDataSubject, string testDataComment, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Functional"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("39725 Verify the Creation of Scheduled Report Monthly by selecting Specific Day M" +
                    "onth", @__tags);
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
  testRunner.Given("I am a shp.entry, shp.entrynortes, shp.inquiry, shp.inquirynorates, operations, s" +
                    "ales, sales management, station owner, or access rrd user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
 testRunner.And("I selected a Custom report from the Select Existing Custom Report drop down list " +
                    "in Customer Invoice page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.And("I clicked on Schedule Report button will be navigated to Weekly Tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.And("I clicked on Monthly Time Period tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.And(string.Format("I entered all the required information{0},{1},{2},{3},{4},{5},{6},{7},{8},{9},{10" +
                        "}", testDataMonth, testDataSpecificDay, testDataHours, testDataMinutes, testDataMeridiem, testDataTo, testDataCC, testDataReplyTo, testDataFormat, testDataSubject, testDataComment), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.When("I click Schedule Report button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 13
 testRunner.Then("the Custom Report will be Scheduled for the selected Specific Month", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("39725 Verify the Creation of Scheduled Report Monthly by selecting Specific Day M" +
            "onth: August")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CustomerInvoice_CreateScheduleReports_Monthly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint80")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("39725")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "August")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataMonth", "August")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataSpecificDay", "15")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataHours", "08")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataMinutes", "00")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataMeridiem", "AM")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataTo", "vasantha.gajaraj@saggezza.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataCC", "vasantha.gajaraj@gmail.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataReplyTo", "vasanth.gajaraj@rrd.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataFormat", "Excel")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataSubject", "TestMonthlyScheduledReportCreation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataComment", "TestingMonthlyReport")]
        public virtual void _39725VerifyTheCreationOfScheduledReportMonthlyBySelectingSpecificDayMonth_August()
        {
#line 6
this._39725VerifyTheCreationOfScheduledReportMonthlyBySelectingSpecificDayMonth("August", "15", "08", "00", "AM", "vasantha.gajaraj@saggezza.com", "vasantha.gajaraj@gmail.com", "vasanth.gajaraj@rrd.com", "Excel", "TestMonthlyScheduledReportCreation", "TestingMonthlyReport", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("39725 Verify the Creation of Scheduled Report Monthly by selecting Specific Day M" +
            "onth: May")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CustomerInvoice_CreateScheduleReports_Monthly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint80")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("39725")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "May")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataMonth", "May")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataSpecificDay", "17")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataHours", "08")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataMinutes", "00")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataMeridiem", "AM")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataTo", "vasantha.gajaraj@saggezza.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataCC", "vasantha.gajaraj@gmail.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataReplyTo", "vasanth.gajaraj@rrd.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataFormat", "Excel")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataSubject", "TestMonthlyScheduledReportCreation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataComment", "TestingMonthlyReport")]
        public virtual void _39725VerifyTheCreationOfScheduledReportMonthlyBySelectingSpecificDayMonth_May()
        {
#line 6
this._39725VerifyTheCreationOfScheduledReportMonthlyBySelectingSpecificDayMonth("May", "17", "08", "00", "AM", "vasantha.gajaraj@saggezza.com", "vasantha.gajaraj@gmail.com", "vasanth.gajaraj@rrd.com", "Excel", "TestMonthlyScheduledReportCreation", "TestingMonthlyReport", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("39725 Verify the Creation of Scheduled Report Monthly by selecting Specific Day M" +
            "onth: June")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CustomerInvoice_CreateScheduleReports_Monthly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint80")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("39725")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "June")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataMonth", "June")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataSpecificDay", "13")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataHours", "02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataMinutes", "00")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataMeridiem", "PM")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataTo", "vasantha.gajaraj@saggezza.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataCC", "vasantha.gajaraj@gmail.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataReplyTo", "vasanth.gajaraj@rrd.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataFormat", "Excel")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataSubject", "TestMonthlyScheduledReportCreation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataComment", "TestingMonthlyReport")]
        public virtual void _39725VerifyTheCreationOfScheduledReportMonthlyBySelectingSpecificDayMonth_June()
        {
#line 6
this._39725VerifyTheCreationOfScheduledReportMonthlyBySelectingSpecificDayMonth("June", "13", "02", "00", "PM", "vasantha.gajaraj@saggezza.com", "vasantha.gajaraj@gmail.com", "vasanth.gajaraj@rrd.com", "Excel", "TestMonthlyScheduledReportCreation", "TestingMonthlyReport", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("39725 Verify the Creation of Scheduled Report Monthly by selecting all the Months" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CustomerInvoice_CreateScheduleReports_Monthly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint80")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("39725")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        public virtual void _39725VerifyTheCreationOfScheduledReportMonthlyBySelectingAllTheMonths()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("39725 Verify the Creation of Scheduled Report Monthly by selecting all the Months" +
                    "", new string[] {
                        "Functional"});
#line 22
 this.ScenarioSetup(scenarioInfo);
#line 23
 testRunner.Given("I am a shp.entry, shp.entrynortes, shp.inquiry, shp.inquirynorates, operations, s" +
                    "ales, sales management, station owner, or access rrd user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 24
 testRunner.And("I selected a Custom report from the Select Existing Custom Report drop down list " +
                    "in Customer Invoice page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
 testRunner.And("I clicked on Schedule Report button will be navigated to Weekly Tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.And("I clicked on Monthly Time Period tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
 testRunner.And("I entered all the required information by selecting all the Months<15>,<08>,<30>," +
                    "<AM>,<test@test.com>,<test123@test.com>,<testabc@test.com>,<Excel>,<TestingSched" +
                    "uledMonthly>,<Test>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
 testRunner.When("I click Schedule Report button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 29
 testRunner.Then("the Custom Report will be Scheduled for all the Months", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void _39725VerifyTheCreationOfScheduledReportMonthlyBySelectingWeekAndWeekDay(string testDataMonth, string testDataWeek, string testDataWeekDay, string testDataHours, string testDataMinutes, string testDataMeridiem, string testDataTo, string testDataCC, string testDataReplyTo, string testDataFormat, string testDataSubject, string testDataComment, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Functional"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("39725 Verify the Creation of Scheduled Report Monthly by selecting Week and Week " +
                    "day", @__tags);
#line 32
 this.ScenarioSetup(scenarioInfo);
#line 33
 testRunner.Given("I am a shp.entry, shp.entrynortes, shp.inquiry, shp.inquirynorates, operations, s" +
                    "ales, sales management, station owner, or access rrd user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 34
 testRunner.And("I selected a Custom report from the Select Existing Custom Report drop down list " +
                    "in Customer Invoice page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 35
 testRunner.And("I clicked on Schedule Report button will be navigated to Weekly Tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 36
 testRunner.And("I clicked on Monthly Time Period tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 37
 testRunner.And(string.Format("I entered the required information by Week and Weed day{0},{1},{2},{3},{4},{5},{6" +
                        "},{7},{8},{9},{10},{11}", testDataMonth, testDataWeek, testDataWeekDay, testDataHours, testDataMinutes, testDataMeridiem, testDataTo, testDataCC, testDataReplyTo, testDataFormat, testDataSubject, testDataComment), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
 testRunner.When("I click Schedule Report button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 39
 testRunner.Then("the Custom Report will be Scheduled for the selected Week and Week day", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("39725 Verify the Creation of Scheduled Report Monthly by selecting Week and Week " +
            "day: August")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CustomerInvoice_CreateScheduleReports_Monthly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint80")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("39725")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "August")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataMonth", "August")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataWeek", "3rd")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataWeekDay", "Wednesday")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataHours", "08")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataMinutes", "00")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataMeridiem", "AM")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataTo", "vasantha.gajaraj@saggezza.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataCC", "vasantha.gajaraj@gmail.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataReplyTo", "vasanth.gajaraj@rrd.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataFormat", "Excel")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataSubject", "TestMonthlyScheduledReportCreation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataComment", "TestingMonthlyReport")]
        public virtual void _39725VerifyTheCreationOfScheduledReportMonthlyBySelectingWeekAndWeekDay_August()
        {
#line 32
 this._39725VerifyTheCreationOfScheduledReportMonthlyBySelectingWeekAndWeekDay("August", "3rd", "Wednesday", "08", "00", "AM", "vasantha.gajaraj@saggezza.com", "vasantha.gajaraj@gmail.com", "vasanth.gajaraj@rrd.com", "Excel", "TestMonthlyScheduledReportCreation", "TestingMonthlyReport", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("39725 Verify the Creation of Scheduled Report Monthly by selecting Week and Week " +
            "day: May")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CustomerInvoice_CreateScheduleReports_Monthly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint80")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("39725")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "May")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataMonth", "May")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataWeek", "3rd")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataWeekDay", "Friday")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataHours", "08")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataMinutes", "00")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataMeridiem", "AM")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataTo", "vasantha.gajaraj@saggezza.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataCC", "vasantha.gajaraj@gmail.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataReplyTo", "vasanth.gajaraj@rrd.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataFormat", "Excel")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataSubject", "TestMonthlyScheduledReportCreation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataComment", "TestingMonthlyReport")]
        public virtual void _39725VerifyTheCreationOfScheduledReportMonthlyBySelectingWeekAndWeekDay_May()
        {
#line 32
 this._39725VerifyTheCreationOfScheduledReportMonthlyBySelectingWeekAndWeekDay("May", "3rd", "Friday", "08", "00", "AM", "vasantha.gajaraj@saggezza.com", "vasantha.gajaraj@gmail.com", "vasanth.gajaraj@rrd.com", "Excel", "TestMonthlyScheduledReportCreation", "TestingMonthlyReport", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("39725 Verify the Creation of Scheduled Report Monthly by selecting Week and Week " +
            "day: June")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CustomerInvoice_CreateScheduleReports_Monthly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint80")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("39725")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "June")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataMonth", "June")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataWeek", "2nd")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataWeekDay", "Wednesday")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataHours", "02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataMinutes", "00")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataMeridiem", "PM")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataTo", "vasantha.gajaraj@saggezza.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataCC", "vasantha.gajaraj@gmail.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataReplyTo", "vasanth.gajaraj@rrd.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataFormat", "Excel")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataSubject", "TestMonthlyScheduledReportCreation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataComment", "TestingMonthlyReport")]
        public virtual void _39725VerifyTheCreationOfScheduledReportMonthlyBySelectingWeekAndWeekDay_June()
        {
#line 32
 this._39725VerifyTheCreationOfScheduledReportMonthlyBySelectingWeekAndWeekDay("June", "2nd", "Wednesday", "02", "00", "PM", "vasantha.gajaraj@saggezza.com", "vasantha.gajaraj@gmail.com", "vasanth.gajaraj@rrd.com", "Excel", "TestMonthlyScheduledReportCreation", "TestingMonthlyReport", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("39725 Verify the Cancel and Schedule Report buttons are Active in Monthly time pe" +
            "riod tab")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CustomerInvoice_CreateScheduleReports_Monthly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint80")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("39725")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("GUI")]
        public virtual void _39725VerifyTheCancelAndScheduleReportButtonsAreActiveInMonthlyTimePeriodTab()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("39725 Verify the Cancel and Schedule Report buttons are Active in Monthly time pe" +
                    "riod tab", new string[] {
                        "GUI"});
#line 48
 this.ScenarioSetup(scenarioInfo);
#line 49
 testRunner.Given("I am a shp.entry, shp.entrynortes, shp.inquiry, shp.inquirynorates, operations, s" +
                    "ales, sales management, station owner, or access rrd user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 50
 testRunner.And("I selected a Custom report from the Select Existing Custom Report drop down list " +
                    "in Customer Invoice page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
 testRunner.And("I clicked on Schedule Report button will be navigated to Weekly Tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 52
 testRunner.When("I click on the Monthly Time Period tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 53
 testRunner.Then("the Cancel and Schedule Report buttons will be Active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void _39725VerifyTheMonthlyScheduledReportCreationForWeekAndWeekdayBySelectingAllMonths(string testDataWeek, string testDataWeekDay, string testDataHours, string testDataMinutes, string testDataMeridiem, string testDataTo, string testDataCC, string testDataReplyTo, string testDataFormat, string testDataSubject, string testDataComment, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Functional"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("39725 Verify the Monthly Scheduled Report creation for Week and Weekday by select" +
                    "ing all Months", @__tags);
#line 56
 this.ScenarioSetup(scenarioInfo);
#line 57
 testRunner.Given("I am a shp.entry, shp.entrynortes, shp.inquiry, shp.inquirynorates, operations, s" +
                    "ales, sales management, station owner, or access rrd user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 58
 testRunner.And("I selected a Custom report from the Select Existing Custom Report drop down list " +
                    "in Customer Invoice page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 59
 testRunner.And("I clicked on Schedule Report button will be navigated to Weekly Tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 60
 testRunner.And("I clicked on the Monthly Time Period tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 61
 testRunner.And(string.Format("I entered the required information by selecting all months Week and Weed day{0},{" +
                        "1},{2},{3},{4},{5},{6},{7},{8},{9},{10}", testDataWeek, testDataWeekDay, testDataHours, testDataMinutes, testDataMeridiem, testDataTo, testDataCC, testDataReplyTo, testDataFormat, testDataSubject, testDataComment), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 62
 testRunner.When("I click Schedule Report button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 63
 testRunner.Then("the Custom Report will be scheduled for selected week and Weekday for the current" +
                    " Month", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("39725 Verify the Monthly Scheduled Report creation for Week and Weekday by select" +
            "ing all Months: 2nd")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CustomerInvoice_CreateScheduleReports_Monthly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint80")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("39725")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "2nd")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataWeek", "2nd")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataWeekDay", "Thursday")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataHours", "01")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataMinutes", "30")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataMeridiem", "AM")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataTo", "vasantha.gajaraj@saggezza.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataCC", "vasantha.gajaraj@gmail.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataReplyTo", "vasanth.gajaraj@rrd.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataFormat", "Excel")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataSubject", "TestMonthlyScheduledReportCreation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataComment", "TestingMonthlyReport")]
        public virtual void _39725VerifyTheMonthlyScheduledReportCreationForWeekAndWeekdayBySelectingAllMonths_2Nd()
        {
#line 56
 this._39725VerifyTheMonthlyScheduledReportCreationForWeekAndWeekdayBySelectingAllMonths("2nd", "Thursday", "01", "30", "AM", "vasantha.gajaraj@saggezza.com", "vasantha.gajaraj@gmail.com", "vasanth.gajaraj@rrd.com", "Excel", "TestMonthlyScheduledReportCreation", "TestingMonthlyReport", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("39725 Verify the Monthly Scheduled Report creation for Week and Weekday by select" +
            "ing all Months: 3rd")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CustomerInvoice_CreateScheduleReports_Monthly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint80")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("39725")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "3rd")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataWeek", "3rd")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataWeekDay", "Wednesday")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataHours", "08")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataMinutes", "00")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataMeridiem", "PM")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataTo", "vasantha.gajaraj@saggezza.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataCC", "vasantha.gajaraj@gmail.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataReplyTo", "vasanth.gajaraj@rrd.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataFormat", "PDF")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataSubject", "TestMonthlyScheduledReportCreation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataComment", "TestingMonthlyReport")]
        public virtual void _39725VerifyTheMonthlyScheduledReportCreationForWeekAndWeekdayBySelectingAllMonths_3Rd()
        {
#line 56
 this._39725VerifyTheMonthlyScheduledReportCreationForWeekAndWeekdayBySelectingAllMonths("3rd", "Wednesday", "08", "00", "PM", "vasantha.gajaraj@saggezza.com", "vasantha.gajaraj@gmail.com", "vasanth.gajaraj@rrd.com", "PDF", "TestMonthlyScheduledReportCreation", "TestingMonthlyReport", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("39725 Verify the Monthly Scheduled Report creation for Week and Weekday by select" +
            "ing all Months: 4th")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CustomerInvoice_CreateScheduleReports_Monthly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint80")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("39725")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "4th")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataWeek", "4th")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataWeekDay", "Wednesday")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataHours", "08")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataMinutes", "00")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataMeridiem", "PM")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataTo", "vasantha.gajaraj@saggezza.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataCC", "vasantha.gajaraj@gmail.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataReplyTo", "vasanth.gajaraj@rrd.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataFormat", "PDF")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataSubject", "TestMonthlyScheduledReportCreation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:testDataComment", "TestingMonthlyReport")]
        public virtual void _39725VerifyTheMonthlyScheduledReportCreationForWeekAndWeekdayBySelectingAllMonths_4Th()
        {
#line 56
 this._39725VerifyTheMonthlyScheduledReportCreationForWeekAndWeekdayBySelectingAllMonths("4th", "Wednesday", "08", "00", "PM", "vasantha.gajaraj@saggezza.com", "vasantha.gajaraj@gmail.com", "vasanth.gajaraj@rrd.com", "PDF", "TestMonthlyScheduledReportCreation", "TestingMonthlyReport", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
