// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CRM.UITest.Scripts.Shipment.AddShipment.AddShipment_PageElements_AllUsers
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class DisplayCustomerNameOnAllPages_StationUsers_ShipmentFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "Display Customer Name On All Pages - Station Users.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Display Customer Name On All Pages - Station Users - Shipment", null, ProgrammingLanguage.CSharp, new string[] {
                        "Sprint21_Ninja",
                        "44621"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "Display Customer Name On All Pages - Station Users - Shipment")))
            {
                global::CRM.UITest.Scripts.Shipment.AddShipment.AddShipment_PageElements_AllUsers.DisplayCustomerNameOnAllPages_StationUsers_ShipmentFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("44621_Verify display of expected default selection in the customer list dropdown " +
            "of Shipment list page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Display Customer Name On All Pages - Station Users - Shipment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint21_Ninja")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("44621")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Acceptance")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("GUI")]
        public virtual void _44621_VerifyDisplayOfExpectedDefaultSelectionInTheCustomerListDropdownOfShipmentListPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("44621_Verify display of expected default selection in the customer list dropdown " +
                    "of Shipment list page", new string[] {
                        "functional",
                        "Acceptance",
                        "GUI"});
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given("I am a sales, sales management, operations, or station owner user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
 testRunner.When("I arrive on the Shipment List page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 8
 testRunner.Then("The default selection in the customer list should be \"Select an account to displa" +
                    "y...\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 9
 testRunner.And("I should no longer have \"Select...\" as an option from the customer drop down list" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("44621_Verify Station - Primary Account - Customer Name displayed on Add Shipment " +
            "page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Display Customer Name On All Pages - Station Users - Shipment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint21_Ninja")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("44621")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Acceptance")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("GUI")]
        public virtual void _44621_VerifyStation_PrimaryAccount_CustomerNameDisplayedOnAddShipmentPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("44621_Verify Station - Primary Account - Customer Name displayed on Add Shipment " +
                    "page", new string[] {
                        "functional",
                        "Acceptance",
                        "GUI"});
#line 12
this.ScenarioSetup(scenarioInfo);
#line 13
 testRunner.Given("I am a sales, sales management, operations, or station owner user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 14
 testRunner.And("I am on the Shipment List page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.And("I have selected a customer from my customer list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
 testRunner.And("I clicked on the Add Shipment button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.And("I clicked on the LTL tile on the Add Shipment page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.When("I am on the Add Shipment (LTL) page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 19
 testRunner.Then("I will see the Station - Primary Account - Customer Name displayed on the page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 20
 testRunner.And("The Station-Primary Account-Customer Name is not editable.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("44621_Verify Station - Primary Account - Customer Name displayed on Shipment Resu" +
            "lt page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Display Customer Name On All Pages - Station Users - Shipment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint21_Ninja")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("44621")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Acceptance")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("GUI")]
        public virtual void _44621_VerifyStation_PrimaryAccount_CustomerNameDisplayedOnShipmentResultPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("44621_Verify Station - Primary Account - Customer Name displayed on Shipment Resu" +
                    "lt page", new string[] {
                        "functional",
                        "Acceptance",
                        "GUI"});
#line 23
this.ScenarioSetup(scenarioInfo);
#line 24
 testRunner.Given("I am a sales, sales management, operations, or station owner user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 25
 testRunner.And("I am on the Shipment List page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.And("I am creating a LTL shipment", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
 testRunner.And("I clicked on the \"View Rates\" button on the Add Shipment (LTL) page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
 testRunner.When("I am on the Shipment Results (LTL) page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 29
 testRunner.Then("I will see the Station - Primary Account - Customer Name getting displayed on pag" +
                    "e", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 30
 testRunner.And("The Station-Primary Account-Customer Name is not editable", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void _44621_VerifyStation_PrimaryAccount_CustomerNameDisplayedOnShipmentReviewAndSubmitPage(string shipmentType, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "functional",
                    "Acceptance",
                    "GUI"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("44621_Verify Station - Primary Account - Customer Name displayed on Shipment Revi" +
                    "ew And Submit page", @__tags);
#line 33
this.ScenarioSetup(scenarioInfo);
#line 34
 testRunner.Given("I am a sales, sales management, operations, or station owner user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 35
 testRunner.And("I am on the Shipment List page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 36
 testRunner.And("I am creating a LTL shipment", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 37
 testRunner.And(string.Format("I clicked on either on Create Shipment or Create Insured Shipment buttons on the " +
                        "Shipment Results (LTL) page {0}", shipmentType), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
 testRunner.When("I am on the Review and Submit (LTL) page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 39
 testRunner.Then("I will see the Station - Primary Account - Customer Name getting displayed on pag" +
                    "e", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 40
 testRunner.And("The Station-Primary Account-Customer Name is not editable", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("44621_Verify Station - Primary Account - Customer Name displayed on Shipment Revi" +
            "ew And Submit page: CreateShipment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Display Customer Name On All Pages - Station Users - Shipment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint21_Ninja")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("44621")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Acceptance")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("GUI")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CreateShipment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ShipmentType", "CreateShipment")]
        public virtual void _44621_VerifyStation_PrimaryAccount_CustomerNameDisplayedOnShipmentReviewAndSubmitPage_CreateShipment()
        {
#line 33
this._44621_VerifyStation_PrimaryAccount_CustomerNameDisplayedOnShipmentReviewAndSubmitPage("CreateShipment", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("44621_Verify Station - Primary Account - Customer Name displayed on Shipment Revi" +
            "ew And Submit page: CreateInsuredShipment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Display Customer Name On All Pages - Station Users - Shipment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint21_Ninja")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("44621")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Acceptance")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("GUI")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CreateInsuredShipment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ShipmentType", "CreateInsuredShipment")]
        public virtual void _44621_VerifyStation_PrimaryAccount_CustomerNameDisplayedOnShipmentReviewAndSubmitPage_CreateInsuredShipment()
        {
#line 33
this._44621_VerifyStation_PrimaryAccount_CustomerNameDisplayedOnShipmentReviewAndSubmitPage("CreateInsuredShipment", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("44621_Verify Station - Primary Account - Customer Name displayed on Shipment Conf" +
            "irmation page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Display Customer Name On All Pages - Station Users - Shipment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint21_Ninja")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("44621")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Acceptance")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("GUI")]
        public virtual void _44621_VerifyStation_PrimaryAccount_CustomerNameDisplayedOnShipmentConfirmationPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("44621_Verify Station - Primary Account - Customer Name displayed on Shipment Conf" +
                    "irmation page", new string[] {
                        "functional",
                        "Acceptance",
                        "GUI"});
#line 48
this.ScenarioSetup(scenarioInfo);
#line 49
 testRunner.Given("that I am a sales, sales management, operations, or station owner user,", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 50
 testRunner.And("I am on the Shipment List page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
 testRunner.And("I am creating a LTL shipment", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 52
 testRunner.And("I clicked on the \"Submit Shipment\" button on the Review and Submit page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 53
 testRunner.When("I am on the Shipment Confirmation (LTL) page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 54
 testRunner.Then("I will see the Station - Primary Account - Customer Name getting displayed on pag" +
                    "e", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 55
 testRunner.And("The Station-Primary Account-Customer Name is not editable", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("44621_Verify Station - Primary Account - Customer Name of the saved quote display" +
            "ed on the page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Display Customer Name On All Pages - Station Users - Shipment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint21_Ninja")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("44621")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Acceptance")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("GUI")]
        public virtual void _44621_VerifyStation_PrimaryAccount_CustomerNameOfTheSavedQuoteDisplayedOnThePage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("44621_Verify Station - Primary Account - Customer Name of the saved quote display" +
                    "ed on the page", new string[] {
                        "functional",
                        "Acceptance",
                        "GUI"});
#line 59
this.ScenarioSetup(scenarioInfo);
#line 60
testRunner.Given("that I am a sales, sales management, operations, or station owner user,", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 61
testRunner.And("I am expanded non expired Quote with Notification accessorial", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 62
testRunner.And("I clicked on the Create Shipment Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 63
testRunner.When("I arrive on the Add Shipment (LTL) page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 64
testRunner.Then("I will see the Station - Primary Account - Customer Name displayed on the page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 65
testRunner.And("The Station-Primary Account-Customer Name is not editable.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("44621_Verify Station - Primary Account - Customer Name of the rate shop displayed" +
            " on the page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Display Customer Name On All Pages - Station Users - Shipment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint21_Ninja")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("44621")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Acceptance")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("GUI")]
        public virtual void _44621_VerifyStation_PrimaryAccount_CustomerNameOfTheRateShopDisplayedOnThePage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("44621_Verify Station - Primary Account - Customer Name of the rate shop displayed" +
                    " on the page", new string[] {
                        "functional",
                        "Acceptance",
                        "GUI"});
#line 68
this.ScenarioSetup(scenarioInfo);
#line 69
 testRunner.Given("that I am a sales, sales management, operations, or station owner user,", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 70
 testRunner.And("I am on the Quote Results (LTL) page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 71
 testRunner.And("I clicked on either Create Shipment or Create Insured Shipment buttons for any di" +
                    "splayed carrier", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 72
 testRunner.When("I arrive on the Add Shipment (LTL) page,", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 73
 testRunner.Then("I will see the Station - Primary Account - Customer Name displayed on the page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 74
 testRunner.And("The Station-Primary Account-Customer Name is not editable.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
