// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CRM.UITest.Scripts.CustomerInvoices
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class AccessRRDUser_CustomerInvoicePageLoadFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "AccessRRDUser - Customer Invoice Page Load.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "AccessRRDUser - Customer Invoice Page Load", null, ProgrammingLanguage.CSharp, new string[] {
                        "41352",
                        "NinjaSprint17"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "AccessRRDUser - Customer Invoice Page Load")))
            {
                global::CRM.UITest.Scripts.CustomerInvoices.AccessRRDUser_CustomerInvoicePageLoadFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("41352_Verify_That the Customer Invoice grid will no longer auto-populate for Acce" +
            "ssRRD User")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AccessRRDUser - Customer Invoice Page Load")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("41352")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NinjaSprint17")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        public virtual void _41352_Verify_ThatTheCustomerInvoiceGridWillNoLongerAuto_PopulateForAccessRRDUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("41352_Verify_That the Customer Invoice grid will no longer auto-populate for Acce" +
                    "ssRRD User", new string[] {
                        "Functional"});
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given("I am an Access RRD user logged in to CRM Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
 testRunner.When("I am on the Customer Invoices list page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 8
 testRunner.Then("the Customer Invoice grid will no longer auto-populate", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("41352_Verify_That the Customer Invoice page has options to select stations, custo" +
            "mer accounts and Display Invoices button for AccessRRD User")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AccessRRDUser - Customer Invoice Page Load")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("41352")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NinjaSprint17")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("GUI")]
        public virtual void _41352_Verify_ThatTheCustomerInvoicePageHasOptionsToSelectStationsCustomerAccountsAndDisplayInvoicesButtonForAccessRRDUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("41352_Verify_That the Customer Invoice page has options to select stations, custo" +
                    "mer accounts and Display Invoices button for AccessRRD User", new string[] {
                        "GUI"});
#line 11
this.ScenarioSetup(scenarioInfo);
#line 12
 testRunner.Given("I am an Access RRD user logged in to CRM Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 13
 testRunner.When("I am on the Customer Invoices list page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 14
 testRunner.Then("I will be presented with an option to select Stations that I am associated to", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 15
 testRunner.And("I will be presented with an option to select Customer Accounts I am associated to" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
 testRunner.And("I will see a Display Invoices button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.And("the Display Invoices button is inactive", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("41352_Verify_Stations dropdown functionality in the Customer Invoice page for Acc" +
            "essRRD User")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AccessRRDUser - Customer Invoice Page Load")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("41352")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NinjaSprint17")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        public virtual void _41352_Verify_StationsDropdownFunctionalityInTheCustomerInvoicePageForAccessRRDUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("41352_Verify_Stations dropdown functionality in the Customer Invoice page for Acc" +
                    "essRRD User", new string[] {
                        "Functional"});
#line 20
this.ScenarioSetup(scenarioInfo);
#line 21
 testRunner.Given("I am an Access RRD user logged in to CRM Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 22
 testRunner.And("I am on the Customer Invoices list page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
 testRunner.When("I click in the Stations dropdown for accessRRD User", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 24
 testRunner.Then("I will see a list of stations associated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 25
 testRunner.And("I have the option to select multiple stations associated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.And("I have the option to search for a station for RRD AccessUser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
 testRunner.And("I am required to select one or more stations", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("41352_Verify_Customer accounts dropdown functionality in the Customer Invoice pag" +
            "e for AccessRRD User")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AccessRRDUser - Customer Invoice Page Load")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("41352")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NinjaSprint17")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        public virtual void _41352_Verify_CustomerAccountsDropdownFunctionalityInTheCustomerInvoicePageForAccessRRDUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("41352_Verify_Customer accounts dropdown functionality in the Customer Invoice pag" +
                    "e for AccessRRD User", new string[] {
                        "Functional"});
#line 30
this.ScenarioSetup(scenarioInfo);
#line 31
 testRunner.Given("I am an Access RRD user logged in to CRM Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 32
 testRunner.And("I am on the Customer Invoices list page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 33
 testRunner.And("I have selected one or more Stations from the Station list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
 testRunner.When("I click in the Customer Accounts field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 35
 testRunner.Then("I will see the selected station names displayed in ascending order", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 36
 testRunner.And("the accounts for each station will be displayed in hierarchical format", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 37
 testRunner.And("the accounts will be displayed in alphabetical order within the hierarchy format", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
 testRunner.And("I am unable to select a station displayed in the Account list for AccessRRDUser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 39
 testRunner.And("I have the option to select one or more accounts", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 40
 testRunner.And("I have the option to search for accounts in dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 41
 testRunner.And("I am required to select at least one account", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("41352_Verify_That the Display Invoice button is active when one or more stations " +
            "and accounts are selected in the Customer Invoice page for AccessRRD User")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AccessRRDUser - Customer Invoice Page Load")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("41352")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NinjaSprint17")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        public virtual void _41352_Verify_ThatTheDisplayInvoiceButtonIsActiveWhenOneOrMoreStationsAndAccountsAreSelectedInTheCustomerInvoicePageForAccessRRDUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("41352_Verify_That the Display Invoice button is active when one or more stations " +
                    "and accounts are selected in the Customer Invoice page for AccessRRD User", new string[] {
                        "Functional"});
#line 44
this.ScenarioSetup(scenarioInfo);
#line 45
 testRunner.Given("I am an Access RRD user logged in to CRM Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 46
 testRunner.And("I am on the Customer Invoices list page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 47
 testRunner.And("I have selected one or more Stations from the Station list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
 testRunner.When("I select a customer from the Customer Accounts dropdown ZZZ - CZar Customer Test", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 49
 testRunner.Then("the Display Invoices button will become active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("41352_Verify_That the invoice grid is populated when Display Invoice button is cl" +
            "icked in the Customer Invoice page for AccessRRD User")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AccessRRDUser - Customer Invoice Page Load")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("41352")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NinjaSprint17")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Regression")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("fixed")]
        public virtual void _41352_Verify_ThatTheInvoiceGridIsPopulatedWhenDisplayInvoiceButtonIsClickedInTheCustomerInvoicePageForAccessRRDUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("41352_Verify_That the invoice grid is populated when Display Invoice button is cl" +
                    "icked in the Customer Invoice page for AccessRRD User", new string[] {
                        "Functional",
                        "Regression",
                        "fixed"});
#line 52
this.ScenarioSetup(scenarioInfo);
#line 53
 testRunner.Given("I am an Access RRD user logged in to CRM Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 54
 testRunner.And("I am on the Customer Invoices list page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 55
 testRunner.And("I have selected one or more Stations from the Station list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 56
 testRunner.And("I select a customer from the Customer Accounts dropdown ZZZ - CZar Customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 57
 testRunner.When("I click on the Display Invoices button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 58
 testRunner.Then("the grid will refresh to populate the associated Customer Invoice details ZZZ - C" +
                    "Zar Customer Test", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("41352_Verify_That the invoice grid is populated with 0 results when Display Invoi" +
            "ce button is clicked in the Customer Invoice page for AccessRRD User")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AccessRRDUser - Customer Invoice Page Load")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("41352")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NinjaSprint17")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        public virtual void _41352_Verify_ThatTheInvoiceGridIsPopulatedWith0ResultsWhenDisplayInvoiceButtonIsClickedInTheCustomerInvoicePageForAccessRRDUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("41352_Verify_That the invoice grid is populated with 0 results when Display Invoi" +
                    "ce button is clicked in the Customer Invoice page for AccessRRD User", new string[] {
                        "Functional"});
#line 61
this.ScenarioSetup(scenarioInfo);
#line 62
 testRunner.Given("I am an Access RRD user logged in to CRM Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 63
 testRunner.And("I am on the Customer Invoices list page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 64
 testRunner.And("I have selected one or more Stations from the Station list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 65
 testRunner.And("I select a customer from the Customer Accounts dropdown ZZZ - GS Customer Test", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 66
 testRunner.When("I click on the Display Invoices button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 67
 testRunner.Then("the grid will refresh to populate zero results for the associated Customer Invoic" +
                    "e details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("41352_Verify the accounts under dropdown on customer invoice page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AccessRRDUser - Customer Invoice Page Load")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("41352")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NinjaSprint17")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("49382")]
        public virtual void _41352_VerifyTheAccountsUnderDropdownOnCustomerInvoicePage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("41352_Verify the accounts under dropdown on customer invoice page", new string[] {
                        "Functional",
                        "49382"});
#line 71
this.ScenarioSetup(scenarioInfo);
#line 72
 testRunner.Given("I am an Access RRD user logged in to CRM Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 73
 testRunner.And("I am on the Customer Invoices list page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 74
 testRunner.And("I selected any Station from the dropdown for accessRRD User", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 75
 testRunner.When("I click on accounts drop down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 76
 testRunner.Then("All the accounts associated to the selected station should be load in drop down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
