// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CRM.UITest.Scripts.CustomerInvoices
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class CustomerInvoice_ExportFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "Customer Invoice - Export.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Customer Invoice - Export", null, ProgrammingLanguage.CSharp, new string[] {
                        "Sprint80",
                        "CustomerInvoiceExport",
                        "40154"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "Customer Invoice - Export")))
            {
                global::CRM.UITest.Scripts.CustomerInvoices.CustomerInvoice_ExportFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("40154 - Verify the export options present in Customer Invoice list page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Customer Invoice - Export")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint80")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("CustomerInvoiceExport")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("40154")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("GUI")]
        public virtual void _40154_VerifyTheExportOptionsPresentInCustomerInvoiceListPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("40154 - Verify the export options present in Customer Invoice list page", new string[] {
                        "GUI"});
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given("I am a shp.entry, shp.entrynortes, shp.inquiry, shp.inquirynorates, operations, s" +
                    "ales, sales management, station owner, or access rrd user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
 testRunner.And("I am on Customer Invoice page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.When("I click on Export drop down arrow", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
 testRunner.Then("I have the option to select All - Excel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 10
 testRunner.And("I have the option to select All - PDF", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.And("I will no longer have an option to select All", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.And("I will no longer have an option to select Displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void _40154_VerifyColumnHeadersOfCustomerInvoiceExcel(string reportName, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "GUI",
                    "Regression",
                    "50087",
                    "PrioritySprint2"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("40154 - Verify column headers of Customer Invoice excel", @__tags);
#line 15
this.ScenarioSetup(scenarioInfo);
#line 16
 testRunner.Given("I am a shp.entry, shp.entrynortes, shp.inquiry, shp.inquirynorates, operations, s" +
                    "ales, sales management, station owner, or access rrd user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 17
 testRunner.And("I am on Customer Invoice page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.And(string.Format("I select a Open Saved Report {0} from the dropdown", reportName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
 testRunner.When("I click on Excel option from the export dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 20
 testRunner.Then("A Customer Invoice excel should get downloaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 21
 testRunner.And("The excel file should contain the following column names - Sales Rep, Account #, " +
                    "Station, Customer #, Customer Name, Invoice Number, Reference ID #, Invoice Date" +
                    ", Due Date, Original Amt, Outstanding Amt, Days Past Due, Dispute Code", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("40154 - Verify column headers of Customer Invoice excel: OpenInvoiceReport")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Customer Invoice - Export")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint80")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("CustomerInvoiceExport")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("40154")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("GUI")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Regression")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("50087")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("PrioritySprint2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "OpenInvoiceReport")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Report Name", "OpenInvoiceReport")]
        public virtual void _40154_VerifyColumnHeadersOfCustomerInvoiceExcel_OpenInvoiceReport()
        {
#line 15
this._40154_VerifyColumnHeadersOfCustomerInvoiceExcel("OpenInvoiceReport", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("40154 - Verify and compare the functionality of Export button when \'All - Excel\' " +
            "option is selected and \'Open\' filer is applied")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Customer Invoice - Export")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint80")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("CustomerInvoiceExport")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("40154")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Acceptance")]
        public virtual void _40154_VerifyAndCompareTheFunctionalityOfExportButtonWhenAll_ExcelOptionIsSelectedAndOpenFilerIsApplied()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("40154 - Verify and compare the functionality of Export button when \'All - Excel\' " +
                    "option is selected and \'Open\' filer is applied", new string[] {
                        "Functional",
                        "Acceptance"});
#line 29
this.ScenarioSetup(scenarioInfo);
#line 30
 testRunner.Given("I am a shp.entry, shp.entrynortes, shp.inquiry, shp.inquirynorates, operations, s" +
                    "ales, sales management, station owner, or access rrd user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 31
 testRunner.And("I am on Customer Invoice page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
 testRunner.And("Open filter is applied", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 33
 testRunner.When("I click on All - Excel option from the export dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 34
 testRunner.Then("A Customer Invoice excel should get downloaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 35
 testRunner.And("Excel sheet count and values should match with the UI count and values of Custome" +
                    "r Invoice list page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("40154 - Verify and compare the functionality of Export button when \'All - Excel\' " +
            "option is selected and \'Closed\' filer is applied")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Customer Invoice - Export")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint80")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("CustomerInvoiceExport")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("40154")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Acceptance")]
        public virtual void _40154_VerifyAndCompareTheFunctionalityOfExportButtonWhenAll_ExcelOptionIsSelectedAndClosedFilerIsApplied()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("40154 - Verify and compare the functionality of Export button when \'All - Excel\' " +
                    "option is selected and \'Closed\' filer is applied", new string[] {
                        "Functional",
                        "Acceptance"});
#line 38
this.ScenarioSetup(scenarioInfo);
#line 39
 testRunner.Given("I am a shp.entry, shp.entrynortes, shp.inquiry, shp.inquirynorates, or access rrd" +
                    " user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 40
 testRunner.And("I am on Customer Invoice page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 41
 testRunner.And("Closed filter is applied", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 42
 testRunner.When("I click on All - Excel option from the export dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 43
 testRunner.Then("A Customer Invoice excel should get downloaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 44
 testRunner.And("Excel sheet count and values should match with UI count and values of Customer In" +
                    "voice list page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("40154 - Verify and compare the functionality of Export button when \'All - Excel\' " +
            "option is selected and \'All\' filer is applied")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Customer Invoice - Export")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint80")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("CustomerInvoiceExport")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("40154")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Acceptance")]
        public virtual void _40154_VerifyAndCompareTheFunctionalityOfExportButtonWhenAll_ExcelOptionIsSelectedAndAllFilerIsApplied()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("40154 - Verify and compare the functionality of Export button when \'All - Excel\' " +
                    "option is selected and \'All\' filer is applied", new string[] {
                        "Functional",
                        "Acceptance"});
#line 47
this.ScenarioSetup(scenarioInfo);
#line 48
 testRunner.Given("I am a shp.entry, shp.entrynortes, shp.inquiry, shp.inquirynorates, operations, s" +
                    "ales, sales management, station owner, or access rrd user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 49
 testRunner.And("I am on Customer Invoice page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 50
 testRunner.And("All filter is applied", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
 testRunner.When("I click on All - Excel option from the export dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 52
 testRunner.Then("A Customer Invoice excel should get downloaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 53
 testRunner.And("Excel sheet count and values should match with the UI count and values of Custome" +
                    "r Invoice list page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("40154 - Verify the functionality of Export button when \'All - PDF\' option is sele" +
            "cted")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Customer Invoice - Export")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint80")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("CustomerInvoiceExport")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("40154")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Functional")]
        public virtual void _40154_VerifyTheFunctionalityOfExportButtonWhenAll_PDFOptionIsSelected()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("40154 - Verify the functionality of Export button when \'All - PDF\' option is sele" +
                    "cted", new string[] {
                        "Functional"});
#line 56
this.ScenarioSetup(scenarioInfo);
#line 57
 testRunner.Given("I am a shp.entry, shp.entrynortes, shp.inquiry, shp.inquirynorates, operations, s" +
                    "ales, sales management, station owner, or access rrd user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 58
 testRunner.And("I am on Customer Invoice page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 59
 testRunner.When("I click on All - PDF option from the export dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 60
 testRunner.Then("A Customer Invoice PDF document should get opened in an other tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("50087 - Verify column headers of Customer Invoice excel when Closed filter is app" +
            "lied")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Customer Invoice - Export")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint80")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("CustomerInvoiceExport")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("40154")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("GUI")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Regression")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("50087")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("PrioritySprint2")]
        public virtual void _50087_VerifyColumnHeadersOfCustomerInvoiceExcelWhenClosedFilterIsApplied()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("50087 - Verify column headers of Customer Invoice excel when Closed filter is app" +
                    "lied", new string[] {
                        "GUI",
                        "Regression",
                        "50087",
                        "PrioritySprint2"});
#line 63
this.ScenarioSetup(scenarioInfo);
#line 64
 testRunner.Given("I am a shp.entry, shp.entrynortes, shp.inquiry, shp.inquirynorates, or access rrd" +
                    " user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 65
 testRunner.And("I am on Customer Invoice page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 66
 testRunner.And("Closed filter is applied", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 67
 testRunner.When("I click on Excel option from the export dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 68
 testRunner.Then("A Customer Invoice excel should get downloaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 69
 testRunner.And("The excel file should contain the following column names - Sales Rep, Account #, " +
                    "Station, Customer #, Customer Name, Invoice Number, Reference ID #, Invoice Date" +
                    ", Due Date, Payment Date, Original Amt, Outstanding Amt, Dispute Code", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void _50087_VerifyTheColumnDaysPastDueIsRemovedAndANewColumnPaymentDateIsAddedNextToDueDateInTheExportedExcelFileForClosedInvoicesSearchedThroughSearchInvoicesSection(string option, string searchText, string openOrClosed, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "GUI",
                    "50087",
                    "PrioritySprint2"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("50087 - Verify the column Days Past Due is removed and a new column Payment Date " +
                    "is added next to Due Date in the exported excel file for Closed invoices searche" +
                    "d through Search Invoices section", @__tags);
#line 72
this.ScenarioSetup(scenarioInfo);
#line 73
 testRunner.Given("I am a operations, sales, sales management, station owner or Access RRD User", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 74
 testRunner.And("I am on Customer Invoice page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 75
 testRunner.And(string.Format("I have selected an {0} from the drop down list", option), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 76
 testRunner.And(string.Format("I choose the {0} radio button", openOrClosed), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 77
 testRunner.And(string.Format("I enter data in the field {0}", searchText), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 78
 testRunner.And("I click on the button search invoices", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 79
 testRunner.When("I click on Excel option from the export dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 80
 testRunner.Then("A Customer Invoice excel should get downloaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 81
 testRunner.And("The excel file should contain the following column names - Sales Rep, Account #, " +
                    "Station, Customer #, Customer Name, Invoice Number, Reference ID #, Invoice Date" +
                    ", Due Date, Payment Date, Original Amt, Outstanding Amt, Dispute Code", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("50087 - Verify the column Days Past Due is removed and a new column Payment Date " +
            "is added next to Due Date in the exported excel file for Closed invoices searche" +
            "d through Search Invoices section: Invoice Number")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Customer Invoice - Export")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint80")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("CustomerInvoiceExport")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("40154")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("GUI")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("50087")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("PrioritySprint2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Invoice Number")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Option", "Invoice Number")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Search Text", "0637726704")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:open or closed", "c")]
        public virtual void _50087_VerifyTheColumnDaysPastDueIsRemovedAndANewColumnPaymentDateIsAddedNextToDueDateInTheExportedExcelFileForClosedInvoicesSearchedThroughSearchInvoicesSection_InvoiceNumber()
        {
#line 72
this._50087_VerifyTheColumnDaysPastDueIsRemovedAndANewColumnPaymentDateIsAddedNextToDueDateInTheExportedExcelFileForClosedInvoicesSearchedThroughSearchInvoicesSection("Invoice Number", "0637726704", "c", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
