//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.UITest.Entities.Proxy
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuredRateCarrier
    {
        public int Id { get; set; }
        public string CarrierName { get; set; }
        public string CarrierCode { get; set; }
        public string CostPerPoundNew { get; set; }
        public string CostPerPoundUsed_ { get; set; }
        public string MaximumLiabilityNew__ { get; set; }
        public string MaximumLiabilityUsed__ { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsExcluded { get; set; }
    }
}
