// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CRM.UITest.Scripts.Shipment.ShipmentDetails
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class TerminalInformation_LTLShipmentDetailsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "Terminal Information - LTL Shipment Details.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Terminal Information - LTL Shipment Details", null, ProgrammingLanguage.CSharp, new string[] {
                        "60031",
                        "Sprint94"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "Terminal Information - LTL Shipment Details")))
            {
                global::CRM.UITest.Scripts.Shipment.ShipmentDetails.TerminalInformation_LTLShipmentDetailsFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void _60031VerifyTheOptionToDisplayTerminalInformationInShipmentDetailsPage(string userType, string userName, string password, string customername, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("60031 Verify the Option to Display Terminal Information in Shipment Details page", exampleTags);
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
testRunner.Given(string.Format("I\'m a shp.inquiry, shp.inquirynorates, shp.entry, shp.entrynorates, sales, sales " +
                        "management, operations, or station owner user{0},{1},{2}", userType, userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
testRunner.When(string.Format("I am on the Shipment Details page of an LTL shipment{0},{1}", userType, customername), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 8
testRunner.Then("I will have an option to display Terminal Information", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("60031 Verify the Option to Display Terminal Information in Shipment Details page:" +
            " Sales")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Terminal Information - LTL Shipment Details")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("60031")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint94")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Sales")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserType", "Sales")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "username-CurrentSprintSales")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "password-CurrentSprintSales")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Customername", "ZZZ - GS Customer Test")]
        public virtual void _60031VerifyTheOptionToDisplayTerminalInformationInShipmentDetailsPage_Sales()
        {
#line 5
this._60031VerifyTheOptionToDisplayTerminalInformationInShipmentDetailsPage("Sales", "username-CurrentSprintSales", "password-CurrentSprintSales", "ZZZ - GS Customer Test", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("60031 Verify the Option to Display Terminal Information in Shipment Details page:" +
            " Internal")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Terminal Information - LTL Shipment Details")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("60031")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint94")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Internal")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserType", "Internal")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "username-CurrentSprintOperations")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "password-CurrentSprintOperations")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Customername", "ZZZ - GS Customer Test")]
        public virtual void _60031VerifyTheOptionToDisplayTerminalInformationInShipmentDetailsPage_Internal()
        {
#line 5
this._60031VerifyTheOptionToDisplayTerminalInformationInShipmentDetailsPage("Internal", "username-CurrentSprintOperations", "password-CurrentSprintOperations", "ZZZ - GS Customer Test", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("60031 Verify the Option to Display Terminal Information in Shipment Details page:" +
            " External")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Terminal Information - LTL Shipment Details")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("60031")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint94")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "External")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserType", "External")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "username-CurrentSprintshpentry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "password-CurrentSprintshpentry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Customername", "ZZZ - GS Customer Test")]
        public virtual void _60031VerifyTheOptionToDisplayTerminalInformationInShipmentDetailsPage_External()
        {
#line 5
this._60031VerifyTheOptionToDisplayTerminalInformationInShipmentDetailsPage("External", "username-CurrentSprintshpentry", "password-CurrentSprintshpentry", "ZZZ - GS Customer Test", ((string[])(null)));
#line hidden
        }
        
        public virtual void _60031VerifyTheLoadingIconAndTerminalInformationFieldsInShipmentDetailsPage(string userType, string userName, string password, string customername, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("60031 Verify the Loading Icon and Terminal Information fields in Shipment Details" +
                    " page", exampleTags);
#line 16
this.ScenarioSetup(scenarioInfo);
#line 18
testRunner.Given(string.Format("I\'m a shp.inquiry, shp.inquirynorates, shp.entry, shp.entrynorates, sales, sales " +
                        "management, operations, or station owner user{0},{1},{2}", userType, userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 19
testRunner.And(string.Format("I am on the shipment Details page of an LTL shipment{0},{1}", userType, customername), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 20
testRunner.When("I click on the option to display terminal Information", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 21
testRunner.Then("I should see page level loading icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 22
testRunner.And("a popup modal is launched to display the terminal information for selected record" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
testRunner.And("the page level loading icon will be closed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 24
testRunner.And("the modal will display the Original Terminal Fields as \"Name\", \"Address1\", \"Addre" +
                    "ss2\", \"City\", \"State\", \"Zip\", \"Country\", \"Contact Name\", \"Phone\", \"Email\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
testRunner.And("the modal will display the Destination Terminal Fields as \"Name\", \"Address1\", \"Ad" +
                    "dress2\", \"City\", \"State\", \"Zip\", \"Country\", \"Contact Name\", \"Phone\", \"Email\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
testRunner.And("I will see <Close> button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("60031 Verify the Loading Icon and Terminal Information fields in Shipment Details" +
            " page: Sales")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Terminal Information - LTL Shipment Details")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("60031")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint94")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Sales")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserType", "Sales")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "username-CurrentSprintSales")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "password-CurrentSprintSales")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Customername", "ZZZ - GS Customer Test")]
        public virtual void _60031VerifyTheLoadingIconAndTerminalInformationFieldsInShipmentDetailsPage_Sales()
        {
#line 16
this._60031VerifyTheLoadingIconAndTerminalInformationFieldsInShipmentDetailsPage("Sales", "username-CurrentSprintSales", "password-CurrentSprintSales", "ZZZ - GS Customer Test", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("60031 Verify the Loading Icon and Terminal Information fields in Shipment Details" +
            " page: Internal")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Terminal Information - LTL Shipment Details")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("60031")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint94")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Internal")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserType", "Internal")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "username-CurrentSprintOperations")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "password-CurrentSprintOperations")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Customername", "ZZZ - GS Customer Test")]
        public virtual void _60031VerifyTheLoadingIconAndTerminalInformationFieldsInShipmentDetailsPage_Internal()
        {
#line 16
this._60031VerifyTheLoadingIconAndTerminalInformationFieldsInShipmentDetailsPage("Internal", "username-CurrentSprintOperations", "password-CurrentSprintOperations", "ZZZ - GS Customer Test", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("60031 Verify the Loading Icon and Terminal Information fields in Shipment Details" +
            " page: External")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Terminal Information - LTL Shipment Details")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("60031")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint94")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "External")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserType", "External")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "username-CurrentSprintshpentry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "password-CurrentSprintshpentry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Customername", "ZZZ - GS Customer Test")]
        public virtual void _60031VerifyTheLoadingIconAndTerminalInformationFieldsInShipmentDetailsPage_External()
        {
#line 16
this._60031VerifyTheLoadingIconAndTerminalInformationFieldsInShipmentDetailsPage("External", "username-CurrentSprintshpentry", "password-CurrentSprintshpentry", "ZZZ - GS Customer Test", ((string[])(null)));
#line hidden
        }
        
        public virtual void _60031VerifyTheTerminalInformationModalClosesWhenIClickOnTheCloseButtonFromTheTerminalInformationModalInShipmentDetailsPage(string userType, string userName, string password, string customername, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("60031 Verify the Terminal Information Modal closes when i click on the Close butt" +
                    "on from the Terminal Information Modal in Shipment Details page", exampleTags);
#line 33
this.ScenarioSetup(scenarioInfo);
#line 34
testRunner.Given(string.Format("I\'m a shp.inquiry, shp.inquirynorates, shp.entry, shp.entrynorates, sales, sales " +
                        "management, operations, or station owner user{0},{1},{2}", userType, userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 35
testRunner.And(string.Format("I am on the shipment Details page of an LTL shipment{0},{1}", userType, customername), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 36
testRunner.And("I clicked on the Terminal Info Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 37
testRunner.And("I am in Terminal Information modal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
testRunner.When("I click Close button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 39
testRunner.Then("the Terminal Information modal will close", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("60031 Verify the Terminal Information Modal closes when i click on the Close butt" +
            "on from the Terminal Information Modal in Shipment Details page: Sales")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Terminal Information - LTL Shipment Details")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("60031")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint94")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Sales")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserType", "Sales")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "username-CurrentSprintSales")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "password-CurrentSprintSales")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Customername", "ZZZ - GS Customer Test")]
        public virtual void _60031VerifyTheTerminalInformationModalClosesWhenIClickOnTheCloseButtonFromTheTerminalInformationModalInShipmentDetailsPage_Sales()
        {
#line 33
this._60031VerifyTheTerminalInformationModalClosesWhenIClickOnTheCloseButtonFromTheTerminalInformationModalInShipmentDetailsPage("Sales", "username-CurrentSprintSales", "password-CurrentSprintSales", "ZZZ - GS Customer Test", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("60031 Verify the Terminal Information Modal closes when i click on the Close butt" +
            "on from the Terminal Information Modal in Shipment Details page: Internal")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Terminal Information - LTL Shipment Details")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("60031")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint94")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Internal")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserType", "Internal")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "username-CurrentSprintOperations")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "password-CurrentSprintOperations")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Customername", "ZZZ - GS Customer Test")]
        public virtual void _60031VerifyTheTerminalInformationModalClosesWhenIClickOnTheCloseButtonFromTheTerminalInformationModalInShipmentDetailsPage_Internal()
        {
#line 33
this._60031VerifyTheTerminalInformationModalClosesWhenIClickOnTheCloseButtonFromTheTerminalInformationModalInShipmentDetailsPage("Internal", "username-CurrentSprintOperations", "password-CurrentSprintOperations", "ZZZ - GS Customer Test", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("60031 Verify the Terminal Information Modal closes when i click on the Close butt" +
            "on from the Terminal Information Modal in Shipment Details page: External")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Terminal Information - LTL Shipment Details")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("60031")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Sprint94")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "External")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserType", "External")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "username-CurrentSprintshpentry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "password-CurrentSprintshpentry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Customername", "ZZZ - GS Customer Test")]
        public virtual void _60031VerifyTheTerminalInformationModalClosesWhenIClickOnTheCloseButtonFromTheTerminalInformationModalInShipmentDetailsPage_External()
        {
#line 33
this._60031VerifyTheTerminalInformationModalClosesWhenIClickOnTheCloseButtonFromTheTerminalInformationModalInShipmentDetailsPage("External", "username-CurrentSprintshpentry", "password-CurrentSprintshpentry", "ZZZ - GS Customer Test", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion

